ministryofjustice/offender-risk-profiler

- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/dao/DataRepository.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/dao/OcgRepository.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/dao/OcgmRepository.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/dao/PathfinderRepository.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/dao/PrasRepository.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/dao/ViperRepository.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/model/ViolenceProfile.java
- src/test/java/uk/gov/justice/digital/hmpps/riskprofiler/dao/OcgmRepositoryTest.java
This is just the reload race condition - I couldnt see a way of handling startup without recoding the camel 'from' config
> Dc 282 race condition

- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/config/HealthInfo.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/dao/DataRepository.java
- src/test/java/uk/gov/justice/digital/hmpps/riskprofiler/config/HealthInfoTest.java
sorted startup using health indicator
> DC-282 Race conditions on starting up risk profiler applications need handling

- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/utils/CorrelationMdcFilter.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/utils/RequestLogFilter.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/utils/UserContextFilter.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/utils/UserMdcFilter.java
Fix filter order so correlation id is present for request/response logger
> CAT-200 Add correlation id

- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/services/NomisService.java
- src/test/java/uk/gov/justice/digital/hmpps/riskprofiler/services/NomisServiceTest.java
Handle no parties being returned , or not found error
> CAT-624 Elite2 NPE when incident has no parties

- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/controllers/ControllerAdvice.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/controllers/RiskProfilerResource.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/model/LifeProfile.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/model/OffenderBooking.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/model/OffenderSentenceTerms.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/model/RiskType.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/services/LifeDecisionTreeService.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/services/NomisService.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/services/PollPrisonersService.java
- src/test/java/uk/gov/justice/digital/hmpps/riskprofiler/services/LifeDecisionTreeServiceTest.java
New service for detecting lifers
> CAT-611 Change logic of recommended cat for life-sentences

- helm_deploy/offender-risk-profiler/templates/deployment.yaml
Reverts ministryofjustice/offender-risk-profiler#92
> Revert "DT-917: Switch out deprecated APIs"

- .circleci/config.yml
- Dockerfile
- build.gradle
- update to use DPS orbs in circleci build
- update Dockerfile to be multistage to minimise bloat from /build
> PAT-931: Update to use DPS orbs

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Update to helm_deploy files to pull quayio image instead of docker image
> PAT-931 update helm-deploy values to pull quay instead of docker image

- .circleci/config.yml
Also updated default branch  to main, removed master and amended the branch merging rule.
> PAT-931: Change master to main

- helm_deploy/offender-risk-profiler/templates/deployment.yaml
- Update deprected Kubernetes API references
> PAT-1015: Update deprected Kubernetes API references

- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/services/PollPrisonersService.java
- src/test/java/uk/gov/justice/digital/hmpps/riskprofiler/services/PollPrisonersServiceTest.java
Omit pathfinder check from nightly batch
> CAT-679 Flag PF cases to security

- build.gradle
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/queue/LocalstackConfig.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/security/WebClientConfiguration.java
- src/main/resources/application-localstack.properties
- src/test/resources/application-test.yml
> CAT-685 Upgrade risk-profiler gradle plugin - Fix event queues

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/events/EventListener.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/services/EscapeDecisionTreeService.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/services/ExtremismDecisionTreeService.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/services/LifeDecisionTreeService.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/services/SocDecisionTreeService.java
- src/main/java/uk/gov/justice/digital/hmpps/riskprofiler/services/ViolenceDecisionTreeService.java
- src/test/java/uk/gov/justice/digital/hmpps/riskprofiler/events/EventListenerTest.java
- src/test/java/uk/gov/justice/digital/hmpps/riskprofiler/services/EscapeDecisionTreeServiceTest.java
- src/test/java/uk/gov/justice/digital/hmpps/riskprofiler/services/LifeDecisionTreeServiceTest.java
- src/test/java/uk/gov/justice/digital/hmpps/riskprofiler/services/SocDecisionTreeServiceTest.java
- src/test/java/uk/gov/justice/digital/hmpps/riskprofiler/services/ViolenceDecisionTreeServiceTest.java
Also bumped dependency versions and converted some unit tests to jupiter
> PAT-1895 Reduce logging to appinsights

- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/controllers/RiskProfilerResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/IncidentResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/ExtremismDecisionTreeService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/ViolenceDecisionTreeService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/rediscli/RedisCli.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/controllers/ResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/controllers/RiskProfilerResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/integration/wiremock/MockServers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/IncidentResponseTest.kt
- src/test/resources/uk/gov/justice/digital/hmpps/riskprofiler/controllers/testGetSoc.json
> Pat 1926 offender risk profiler convert to kotlin 8

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
Just upgrade some deps to trigger a deploy
> PAT-2104 Migrate categorisation namespace to live cluster

- .circleci/config.yml
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- helm_deploy/offender-risk-profiler/Chart.yaml
- helm_deploy/offender-risk-profiler/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/controllers/BatchHelperResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/controllers/RiskProfilerResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/Alert.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/ErrorResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/EscapeProfile.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/ExtremismProfile.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/LifeProfile.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/OffenderBooking.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/OffenderSentenceTerms.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/RiskProfile.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/SocProfile.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/ViolenceProfile.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/security/ResourceServerConfiguration.kt
- src/main/resources/application.properties
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/events/QueueAdminServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/NomisServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/PollPrisonersServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/SocDecisionTreeServiceTest.kt
- gradle-spring-boot with new test assertions,
- springfox to spring docs
- misc dependency bumps
> Pat 2125 risk profiler upgrades

- helm_deploy/offender-risk-profiler/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/ExtremismDecisionTreeService.kt
> PAT-2149 Deserialisation error for pathfinder response

- build.gradle.kts
`4.1.4`
- https://github.com/ministryofjustice/dps-gradle-spring-boot/blob/main/release-notes/4.1.4.md
- https://plugins.gradle.org/plugin/uk.gov.justice.hmpps.gradle-spring-boot/4.1.4
- ~https://plugins.gradle.org/plugin/uk.gov.justice.hmpps.gradle-spring-boot/4.1.4-beta~
> SED-16 - Updated hmpps.gradle-spring-boot to 4.1.4

- build.gradle.kts
hmpps.gradle-spring-boot 4.1.5-beta-2
spring/jpa 1.6.21
> ⬆  GSP Update

- build.gradle.kts
https://plugins.gradle.org/plugin/uk.gov.justice.hmpps.gradle-spring-boot/4.1.5-beta-3
> [DSE-65] Update build.gradle.kts

- .circleci/config.yml
- Dockerfile
- https://circleci.com/developer/orbs/orb/ministryofjustice/hmpps?version=5.1.0
> DSE-158 - Orb from 3.14 to 5.1

- build.gradle.kts
- uk.gov.justice.hmpps.gradle-spring-boot from 4.1.6 to 4.1.7
- shedlock-spring from 4.34.0 to 4.35.0
- shedlock-provider-jdbc-template from 4.34.0 to 4.35.0
- localstack from 1.17.1 to 1.17.2
Closes #199, #200, #201, #202
> Bumped Deps

- build.gradle.kts
- SB 4.2.0
- postgresql 42.3.6
- camel 3.17.0
> [CAT-733] Bump Deps

- build.gradle.kts
- uk.gov.justice.hmpps.gradle-spring-boot.gradle.plugin - 4.2.0 => 4.2.1
- flyway-core - 8.5.11 => 8.5.12
- springdoc-openapi-kotlin - 1.6.8 => 1.6.9
- springdoc-openapi-security - 1.6.8 => 1.6.9
- springdoc-openapi-ui - 1.6.8 => 1.6.9
> [CAT-761] Dep Bumps

- README.md
CAT-1452 modified read.me to force a build to update docker image
> CAT-1452 modified read.me to force a build

- build.gradle.kts
> Cat 1488 owasp updates

- helm_deploy/offender-risk-profiler/values.yaml
> aSI-768_add_productid_to_values_yaml

- .circleci/config.yml
Change to allow a develop branch to be deployed to dev for risk profiler.
> deploy_to_develop_branch

- .circleci/config.yml
Moving to latest version of orb
> SI-1030-move-to-latest-orb

- applicationinsights.dev.json
- build.gradle.kts
- helm_deploy/offender-risk-profiler/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/RestResponsePage.kt
Copying this from the template kotlin app
> App insights connection string and config

- .editorconfig
- .gitignore
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/clent/PrisonerAlertsApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/config/HealthCheck.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/dto/prisonerAlert/PrisonerAlertCodeSummaryDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/dto/prisonerAlert/PrisonerAlertResponseDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/mappers/prisonerAlert/PrisonerAlertResponseDtoMapper.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/Alert.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/model/RestPage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/security/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/EscapeDecisionTreeService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/NomisService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/SocDecisionTreeService.kt
- src/main/resources/application-localstack.properties
- src/main/resources/application.properties
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/controllers/RiskProfilerResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/factories/dto/prisonerAlert/TestPrisonerAlertCodeSummaryDtoFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/factories/dto/prisonerAlert/TestPrisonerAlertResponseDtoFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/factories/model/TestAlertFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/integration/HealthIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/integration/wiremock/MockServers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/integration/wiremock/MockUtility.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/EscapeDecisionTreeServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/NomisServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/PollPrisonersServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/riskprofiler/services/SocDecisionTreeServiceTest.kt
Updating the alerts endpoint from the deprecated one on prison API to the new prisoner alerts api, the role has already been added to the client.
> Si 1387 update alerts endpoint
